### ISSUE TITLE
Offline mode is useless

### ISSUE THREAD

**Issue by Pinkbyte** [dngulin/ttyhlauncher#34]
In short: offline mode requires Internet connection or it would not work.

Symptoms: long loading to main window(around 3 minutes, maybe more) and constant 'client needs updating' messages after click 'Login'. Which, when hit 'Update' will obviously fail.

Test setup is easy - either unplug Internet link or interrupt connection to master server in other way before launcher start(for example - blackhole route to master server or DNS if you want go wild)

Reproduced on 1.1.0 and current master(90e4b285be769855949ff365b55cff0fc8f70a00)

**Comment by dngulin** [comment]
The issue looks like a solved in bb27ea9d322bb0e0bd99f1132679fea761949273

**Comment by Pinkbyte** [comment]
Nice, now it does not stuck, however, that does not solve problem, now it throws this:

[13:18:44] Пусковая установка >> Не удалось проверить контрольную сумму для <path to changed file>
[13:18:44] Пусковая установка >> Требуется обновление! Файлы клиента устарели.

And, obviously, update dialog appears.

Reproduce steps:
1. Update client, run it, make sure that it does not get any updates from server(e.g. it's fully updated)
2. Set 'offline mode', exit client
3. Make changes on server
4. Run client again and see that it does not help

Checkbox 'Check game resources before start' may be in any state - it does not matter, error is the same

**Comment by Pinkbyte** [comment]
I can confirm that issue is fixed in fb979ca277f00e409a5096c5084eed33691f976a
